### ISSUE TITLE
Default config of nginx doesn't include sites-enabled folder

### ISSUE THREAD

**Issue by serchavalos** [vfarcic/continuous-deployment#2]
Hi again Viktor!

Thanks for replying to my previous bug. Although that fix got the proxy server up and running, I noticed your nginx config was ignore. This is the image I got:
![image 2015-04-30 at 5 54 31 pm](https://cloud.githubusercontent.com/assets/587388/7416798/2b194ac0-ef62-11e4-89ec-ab0c9ab173eb.png)

When I output the default nginx config I saw sites-enabled folder was not included:

```
$ docker run --name nginx -p 80:80 -v /etc/nginx/sites-enabled:/etc/nginx/sites-enabled -v /etc/nginx/certs-enabled:/etc/nginx/certs-enabled -v /var/log/nginx:/var/log/nginx nginx cat /etc/nginx/nginx.conf

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```

So I solved it by creating in my vagrant machine a soft-link between `bdd_assistant.conf` and `default.conf` but I'm sure you know a much better approach.

Regards,

// Sergio

**Comment by vfarcic** [comment]
Few months ago Docker changed all their "official" images. Before they were dockerfile/SOMETHING and now they are simply SOMETHING (without dockerfile). That introduced a lot of problems since they also changed definitions of some of those images. nginx is one of those. Until you sent me this email I was not aware that sites-enabled directory is now conf.d. Anyways, the correct command is now:

``` bash
docker run --name nginx -p 80:80 -v /etc/nginx/sites-enabled:/etc/nginx/conf.d -v /etc/nginx/certs-enabled:/etc/nginx/certs -v /var/log/nginx:/var/log/nginx nginx
```

I updated the GitHub repository. Can you please try it out and let me know if it worked out?

**Comment by serchavalos** [comment]
Yes, it fixed it. Thanks again Viktor!
